const wardAreaMappings = [
  { ward: 1, area: 'Preet Vihar Ajnala Road' },
  { ward: 2, area: 'Malanwali' },
  { ward: 3, area: 'Guru Amardass Avenue Ajnala Road' },
  { ward: 4, area: 'Hide Market' },
  { ward: 5, area: 'Dosanda Singh Road' },
  { ward: 6, area: 'Basant Avenue' },
  { ward: 7, area: 'Faizpura' },
  { ward: 8, area: 'Akash Avenue' },
  { ward: 9, area: 'Friends Colony Majitha Road' },
  { ward: 10, area: 'Moon Avenue' },
  { ward: 11, area: 'Hukam Singh Road' },
  { ward: 12, area: 'Majitha Road Tungbala' },
  { ward: 13, area: 'Sandhu Colony Majitha Road' },
  { ward: 14, area: 'Friends Colony Majitha Road' },
  { ward: 15, area: 'Rajinder Nagar' },
  { ward: 16, area: 'New Jawahar Nagar' },
  { ward: 17, area: 'Mustafabad Batala Road' },
  { ward: 18, area: 'Verka' },
  { ward: 19, area: 'Greenland' },
  { ward: 20, area: 'Vallah' },
  { ward: 21, area: 'Khoo Jauda Phatak' },
  { ward: 22, area: 'Sandhu Avenue' },
  { ward: 23, area: 'New Pawan Nagar' },
  { ward: 24, area: 'Judge Nagar' },
  { ward: 25, area: 'New Kangra Colony' },
  { ward: 26, area: 'Sharif Pura' },
  { ward: 27, area: 'Maqbool Pura' },
  { ward: 28, area: 'New Tehsil Pura' },
  { ward: 29, area: 'Kashmir Avenue' },
  { ward: 30, area: 'Kot Karnail Singh' },
  { ward: 31, area: 'Azad Nagar' },
  { ward: 32, area: 'New Gobind Nagar' },
  { ward: 33, area: 'Abadi Rasulpura Rohi' },
  { ward: 34, area: 'Dalip Avenue' },
  { ward: 35, area: 'New Amritsar' },
  { ward: 36, area: 'Darshan Avenue' },
  { ward: 37, area: 'Patti Dadu Jalla' },
  { ward: 38, area: 'Khalsa Nagar' },
  { ward: 39, area: 'Subash Colony' },
  { ward: 40, area: 'Kot Mit Singh' },
  { ward: 41, area: 'New Jaspal Nagar' },
  { ward: 42, area: 'Kot Atma Ram' },
  { ward: 43, area: 'Shaheed Udham Singh Nagar' },
  { ward: 44, area: 'Guru Arjun Dev Nagar' },
  { ward: 45, area: 'Teacher Nanak Colony' },
  { ward: 46, area: 'Chowk Manna Singh' },
  { ward: 47, area: 'Guru Ramdas Nagar' },
  { ward: 48, area: 'Joura Pipal' },
  { ward: 49, area: 'Munshian Bazar' },
  { ward: 50, area: 'Gillwali Gate' },
  { ward: 51, area: 'Sahibzada Fateh Singh Nagar' },
  { ward: 52, area: 'Rani Ka Bagh' },
  { ward: 53, area: 'Shaheed Udham Singh Colony' },
  { ward: 54, area: 'Inside Gate Hakima' },
  { ward: 55, area: 'Qilla Bhangea' },
  { ward: 56, area: 'Killa Bhangian' },
  { ward: 57, area: 'Beri Gate' },
  { ward: 58, area: 'Inside Sultanwind Gate' },
  { ward: 59, area: 'Kot Mana Singh' },
  { ward: 60, area: 'Kashmir Avenue' },
  { ward: 61, area: 'Shivala Colony' },
  { ward: 62, area: 'Dhariwal Hospital Area' },
  { ward: 63, area: 'Islamabad' },
  { ward: 64, area: 'Model Town' },
  { ward: 65, area: 'Putlighar' },
  { ward: 66, area: 'Kabir Park' },
  { ward: 67, area: 'Islamabad' },
  { ward: 68, area: 'Amrik Singh Nagar' },
  { ward: 69, area: 'Meharpura' },
  { ward: 70, area: 'Chota Haripura' },
  { ward: 71, area: 'Guru Nanakpura' },
  { ward: 72, area: 'Dhapai' },
  { ward: 73, area: 'Baba Jiwan Singh Colony' },
  { ward: 74, area: 'Holicity Pearl' },
  { ward: 75, area: 'Hargobindpura' },
  { ward: 76, area: 'Kot Khalsa' },
  { ward: 77, area: 'Chheharta' },
  { ward: 78, area: 'Japanese Avenue' },
  { ward: 79, area: 'Old Lal Mill' },
  { ward: 80, area: 'New Ranjitpura' },
  { ward: 81, area: 'Shamsher Nagar' },
  { ward: 82, area: 'Village Kale' },
  { ward: 83, area: 'Dashmesh Nagar' },
  { ward: 84, area: 'Kabir Park' },
  { ward: 85, area: 'New Anmol Enclave' }
];

module.exports = wardAreaMappings;
