export const councillorsData = [
  {
    id: 1,
    name: 'Smt. Kuljit Kaur',
    wardNumber: 1,
    area: 'Preet Vihar Ajnala Road',
    address: 'Preet Vihar Ajnala Road, Amritsar',
    totalComplaints: 32,
    resolvedComplaints: 20,
    pendingComplaints: 7,
    inProgressComplaints: 5,
    status: 'Active'
  },
  {
    id: 2,
    name: 'Sh. Amarjit Singh',
    wardNumber: 2,
    area: 'Malanwali',
    address: 'VPO Malanwali, Amritsar',
    totalComplaints: 26,
    resolvedComplaints: 15,
    pendingComplaints: 6,
    inProgressComplaints: 5,
    status: 'Active'
  },
  {
    id: 3,
    name: 'Smt. Navdeep Kaur',
    wardNumber: 3,
    area: 'Guru Amardass Avenue Ajnala Road',
    address: 'D-1 Guru Amardass Avenue Ajnala Road, Amritsar',
    totalComplaints: 29,
    resolvedComplaints: 17,
    pendingComplaints: 7,
    inProgressComplaints: 5,
    status: 'Active'
  },
  {
    id: 4,
    name: 'Sh. Mandeep Singh Ahuja',
    wardNumber: 4,
    area: 'Hide Market',
    address: '48 Hide Market, Amritsar',
    totalComplaints: 34,
    resolvedComplaints: 22,
    pendingComplaints: 6,
    inProgressComplaints: 6,
    status: 'Active'
  },
  {
    id: 5,
    name: 'Smt. Kriti Arora',
    wardNumber: 5,
    area: 'Dosanda Singh Road',
    address: '38/9 A Dosanda Singh Road, Amritsar',
    totalComplaints: 24,
    resolvedComplaints: 14,
    pendingComplaints: 5,
    inProgressComplaints: 5,
    status: 'Active'
  },
  {
    id: 6,
    name: 'Sh. Amandeep Aery',
    wardNumber: 6,
    area: 'Basant Avenue',
    address: '595 Basant Avenue, Amritsar',
    totalComplaints: 31,
    resolvedComplaints: 19,
    pendingComplaints: 6,
    inProgressComplaints: 6,
    status: 'Active'
  },
  {
    id: 7,
    name: 'Smt. Kajal',
    wardNumber: 7,
    area: 'Faizpura',
    address: '43 Rattan Singh Chowk Navi Abadi Faizpura, Amritsar',
    totalComplaints: 27,
    resolvedComplaints: 16,
    pendingComplaints: 6,
    inProgressComplaints: 5,
    status: 'Active'
  },
  {
    id: 8,
    name: 'Sh. Balwinder Singh',
    wardNumber: 8,
    area: 'Akash Avenue',
    address: '383 Akash Avenue Fatehgarh Churian Road, Amritsar',
    totalComplaints: 30,
    resolvedComplaints: 18,
    pendingComplaints: 7,
    inProgressComplaints: 5,
    status: 'Active'
  },
  {
    id: 9,
    name: 'Dr. Shobit Kaur',
    wardNumber: 9,
    area: 'Friends Colony Majitha Road',
    address: 'F 13/1 Friends Colony Majitha Road, Amritsar',
    totalComplaints: 22,
    resolvedComplaints: 13,
    pendingComplaints: 4,
    inProgressComplaints: 5,
    status: 'Active'
  },
  {
    id: 10,
    name: 'Smt. Shruti Vij',
    wardNumber: 10,
    area: 'Moon Avenue',
    address: 'House No. 248 Moon Avenue, Majitha Road, Amritsar',
    totalComplaints: 28,
    resolvedComplaints: 17,
    pendingComplaints: 6,
    inProgressComplaints: 5,
    status: 'Active'
  },
  {
    id: 11,
    name: 'Smt. Priyanka Sharma (Senior Deputy Mayor)',
    wardNumber: 11,
    area: 'Hukam Singh Road',
    address: '462 B 16 Hukam Singh Road, Amritsar',
    totalComplaints: 36,
    resolvedComplaints: 24,
    pendingComplaints: 6,
    inProgressComplaints: 6,
    status: 'Active'
  },
  {
    id: 12,
    name: 'Sh. Narinder Singh Tung',
    wardNumber: 12,
    area: 'Majitha Road Tungbala',
    address: 'F 19/167 Majitha Road Tungbala, Amritsar',
    totalComplaints: 25,
    resolvedComplaints: 15,
    pendingComplaints: 5,
    inProgressComplaints: 5,
    status: 'Active'
  },
  {
    id: 13,
    name: 'Smt. Gurwinder Kaur',
    wardNumber: 13,
    area: 'Sandhu Colony Majitha Road',
    address: 'H No. 1185 Sandhu Colony Majitha Road, Amritsar',
    totalComplaints: 29,
    resolvedComplaints: 18,
    pendingComplaints: 6,
    inProgressComplaints: 5,
    status: 'Active'
  },
  {
    id: 14,
    name: 'Sh. Rajkanwal Preetpal Singh Sandhu',
    wardNumber: 14,
    area: 'Friends Colony Majitha Road',
    address: 'F 13/1 Friends Colony Majitha Road, Amritsar',
    totalComplaints: 33,
    resolvedComplaints: 21,
    pendingComplaints: 6,
    inProgressComplaints: 6,
    status: 'Active'
  },
  {
    id: 15,
    name: 'Smt. Rama',
    wardNumber: 15,
    area: 'Rajinder Nagar',
    address: 'F-9/567, Gali No. 5, Batala Road, Rajinder Nagar, Amritsar',
    totalComplaints: 21,
    resolvedComplaints: 12,
    pendingComplaints: 4,
    inProgressComplaints: 5,
    status: 'Active'
  },
  {
    id: 16,
    name: 'Sh. Sandeep Sharma',
    wardNumber: 16,
    area: 'New Jawahar Nagar',
    address: '23/71 New Jawahar Nagar Phase No. 2 Batala Road, Amritsar',
    totalComplaints: 35,
    resolvedComplaints: 23,
    pendingComplaints: 6,
    inProgressComplaints: 6,
    status: 'Active'
  },
  {
    id: 17,
    name: 'Smt. Anita Kumari',
    wardNumber: 17,
    area: 'Mustafabad Batala Road',
    address: 'F-22/767 Gali No. 3 Mustafabad Batala Road, Amritsar',
    totalComplaints: 23,
    resolvedComplaints: 14,
    pendingComplaints: 4,
    inProgressComplaints: 5,
    status: 'Active'
  },
  {
    id: 18,
    name: 'Sh. Navdeep Singh',
    wardNumber: 18,
    area: 'Verka',
    address: '01/14 Opp. Gurudwara Nanaksar, Verka, Amritsar',
    totalComplaints: 27,
    resolvedComplaints: 16,
    pendingComplaints: 5,
    inProgressComplaints: 6,
    status: 'Active'
  },
  {
    id: 19,
    name: 'Smt. Navjeet Kaur',
    wardNumber: 19,
    area: 'Greenland',
    address: '180, Greenland, Opp. Fortis Hospital, Amritsar',
    totalComplaints: 31,
    resolvedComplaints: 19,
    pendingComplaints: 6,
    inProgressComplaints: 6,
    status: 'Active'
  },
  {
    id: 20,
    name: 'Sh. Gurinder Singh',
    wardNumber: 20,
    area: 'Vallah',
    address: 'H. No. 786, Near Dharamshala, Vallah, Amritsar',
    totalComplaints: 24,
    resolvedComplaints: 14,
    pendingComplaints: 5,
    inProgressComplaints: 5,
    status: 'Active'
  },  {
    id: 21,
    name: "Smt. Kulwinder Kaur",
    wardNumber: 21,
    area: "Khoo Jauda Phatak",
    address: "40 Khoo, Near Jauda Phatak, Amritsar",
    totalComplaints: 28,
    resolvedComplaints: 17,
    pendingComplaints: 6,
    inProgressComplaints: 5,
    status: "Active",
  },
  {
    id: 22,
    name: "Sh. Sujinder Bidlan",
    wardNumber: 22,
    area: "Sandhu Avenue",
    address: "243, Sandhu Avenue, Gali No. 1, Batala Road, Amritsar",
    totalComplaints: 31,
    resolvedComplaints: 20,
    pendingComplaints: 6,
    inProgressComplaints: 5,
    status: "Active",
  },
  {
    id: 23,
    name: "Smt. Kulwinder Kaur",
    wardNumber: 23,
    area: "New Pawan Nagar",
    address: "New Pawan Nagar, Amritsar",
    totalComplaints: 24,
    resolvedComplaints: 14,
    pendingComplaints: 5,
    inProgressComplaints: 5,
    status: "Active",
  },
  {
    id: 24,
    name: "Sh. Satnam Singh",
    wardNumber: 24,
    area: "Judge Nagar",
    address: "H.No. H-4, 1281, Gali No. 1, Jaura Phatak, Judge Nagar, Amritsar",
    totalComplaints: 27,
    resolvedComplaints: 16,
    pendingComplaints: 5,
    inProgressComplaints: 6,
    status: "Active",
  },
  {
    id: 25,
    name: "Smt. Monika Sharma",
    wardNumber: 25,
    area: "New Kangra Colony",
    address: "Plot No. 43-C, New Kangra Colony, Batala Road, Amritsar",
    totalComplaints: 29,
    resolvedComplaints: 18,
    pendingComplaints: 6,
    inProgressComplaints: 5,
    status: "Active",
  },
  {
    id: 26,
    name: "Sh. Jatinder Singh (Mayor)",
    wardNumber: 26,
    area: "Sharif Pura",
    address: "2307, Gali No. 4, Sharif Pura, Amritsar",
    totalComplaints: 38,
    resolvedComplaints: 26,
    pendingComplaints: 6,
    inProgressComplaints: 6,
    status: "Active",
  },
  {
    id: 27,
    name: "Smt. Preet Kaur",
    wardNumber: 27,
    area: "Maqbool Pura",
    address: "3481/15 Gali No. 5, Maqbool Pura, Ram Talal, Mehta Road, Amritsar",
    totalComplaints: 30,
    resolvedComplaints: 19,
    pendingComplaints: 6,
    inProgressComplaints: 5,
    status: "Active",
  },
  {
    id: 28,
    name: "Sh. Saurabh Madaan Mithu",
    wardNumber: 28,
    area: "New Tehsil Pura",
    address: "76, New Tehsil Pura, Amritsar",
    totalComplaints: 25,
    resolvedComplaints: 15,
    pendingComplaints: 5,
    inProgressComplaints: 5,
    status: "Active",
  },
  {
    id: 29,
    name: "Smt. Shweta",
    wardNumber: 29,
    area: "Kashmir Avenue",
    address: "364/5 F7 Kashmir Avenue, Amritsar",
    totalComplaints: 28,
    resolvedComplaints: 17,
    pendingComplaints: 6,
    inProgressComplaints: 5,
    status: "Active",
  },
  {
    id: 30,
    name: "Sh. Avtar Singh",
    wardNumber: 30,
    area: "Kot Karnail Singh",
    address: "L12/32 Kot Karnail Singh, Sultanwind Road, Amritsar",
    totalComplaints: 33,
    resolvedComplaints: 21,
    pendingComplaints: 6,
    inProgressComplaints: 6,
    status: "Active",
  },
  {
    id: 31,
    name: "Smt. Sukhbir Kaur",
    wardNumber: 31,
    area: "Azad Nagar",
    address: "H.N. 425 Azad Nagar, Sultanwind Road, Amritsar",
    totalComplaints: 26,
    resolvedComplaints: 15,
    pendingComplaints: 6,
    inProgressComplaints: 5,
    status: "Active",
  },
  {
    id: 32,
    name: "Sh. Jagmeet Singh",
    wardNumber: 32,
    area: "New Gobind Nagar",
    address: "5/187 New Gobind Nagar, Sultanwind Road, Amritsar",
    totalComplaints: 31,
    resolvedComplaints: 20,
    pendingComplaints: 6,
    inProgressComplaints: 5,
    status: "Active",
  },
  {
    id: 33,
    name: "Smt. Ashnoor Kaur",
    wardNumber: 33,
    area: "Abadi Rasulpura Rohi",
    address: "H No-1, Near Sabzi Mandi Vallah, Abadi Rasulpura Rohi, Amritsar",
    totalComplaints: 23,
    resolvedComplaints: 13,
    pendingComplaints: 5,
    inProgressComplaints: 5,
    status: "Active",
  },
  {
    id: 34,
    name: "Sh. Amritpal Singh",
    wardNumber: 34,
    area: "Dalip Avenue",
    address: "55 Foot Road, GT Road, Dalip Avenue, Amritsar",
    totalComplaints: 34,
    resolvedComplaints: 22,
    pendingComplaints: 6,
    inProgressComplaints: 6,
    status: "Active",
  },
  {
    id: 35,
    name: "Smt. Amarji Kaur",
    wardNumber: 35,
    area: "New Amritsar",
    address: "36, UGF, HIG Flats, B Block, New Amritsar",
    totalComplaints: 22,
    resolvedComplaints: 13,
    pendingComplaints: 4,
    inProgressComplaints: 5,
    status: "Active",
  },
  {
    id: 36,
    name: "Sh. Ashok Kumar",
    wardNumber: 36,
    area: "Darshan Avenue",
    address: "Darshan Avenue, O/S Honda City Agency, GT Road, Amritsar",
    totalComplaints: 30,
    resolvedComplaints: 19,
    pendingComplaints: 6,
    inProgressComplaints: 5,
    status: "Active",
  },
  {
    id: 37,
    name: "Smt. Gurjit Kaur",
    wardNumber: 37,
    area: "Patti Dadu Jalla",
    address: "Patti Dadu Jalla, Sultanwind Pind, Amritsar",
    totalComplaints: 21,
    resolvedComplaints: 12,
    pendingComplaints: 4,
    inProgressComplaints: 5,
    status: "Active",
  },
  {
    id: 38,
    name: "Sh. Bhagwant Singh",
    wardNumber: 38,
    area: "Khalsa Nagar",
    address: "H.No. 485, Khalsa Nagar, Kot Mit Singh, Amritsar",
    totalComplaints: 29,
    resolvedComplaints: 18,
    pendingComplaints: 6,
    inProgressComplaints: 5,
    status: "Active",
  },
  {
    id: 39,
    name: "Smt. Manpreet Kaur",
    wardNumber: 39,
    area: "Subash Colony",
    address: "Subash Colony, Sultanwind Pind, Amritsar",
    totalComplaints: 24,
    resolvedComplaints: 14,
    pendingComplaints: 5,
    inProgressComplaints: 5,
    status: "Active",
  },
  {
    id: 40,
    name: "Sh. Gurwinder Singh",
    wardNumber: 40,
    area: "Kot Mit Singh",
    address: "H.No. 1, Kot Mit Singh, Amritsar",
    totalComplaints: 27,
    resolvedComplaints: 16,
    pendingComplaints: 5,
    inProgressComplaints: 6,
    status: "Active",
  },
  {
    id: 41,
    name: "Smt. Sukhwinder Kaur",
    wardNumber: 41,
    area: "New Jaspal Nagar",
    address: "H.No. L3/842, New Jaspal Nagar, Sultanwind Road, Amritsar",
    totalComplaints: 28,
    resolvedComplaints: 17,
    pendingComplaints: 5,
    inProgressComplaints: 6,
    status: "Active",
  },
  {
    id: 42,
    name: "Sh. Gagandeep Singh",
    wardNumber: 42,
    area: "Kot Atma Ram",
    address: "198, Kot Atma Ram, Sultanwind Road, Amritsar",
    totalComplaints: 31,
    resolvedComplaints: 20,
    pendingComplaints: 6,
    inProgressComplaints: 5,
    status: "Active",
  },
  {
    id: 43,
    name: "Sh. Inderjit Singh",
    wardNumber: 43,
    area: "Shaheed Udham Singh Nagar",
    address: "H.No. L-4/1825, Gali No. 4, Shaheed Udham Singh Nagar, Amritsar",
    totalComplaints: 25,
    resolvedComplaints: 15,
    pendingComplaints: 5,
    inProgressComplaints: 5,
    status: "Active",
  },
  {
    id: 44,
    name: "Sh. Jaswinder Singh Gill",
    wardNumber: 44,
    area: "Guru Arjun Dev Nagar",
    address: "H.No. 322, Gali No. 3, Guru Arjun Dev Nagar, Tarn Taran Road, Amritsar",
    totalComplaints: 33,
    resolvedComplaints: 21,
    pendingComplaints: 6,
    inProgressComplaints: 6,
    status: "Active",
  },
  {
    id: 45,
    name: "Smt. Sukhbir Kaur",
    wardNumber: 45,
    area: "Teacher Nanak Colony",
    address: "H.No. M2/1 Near Taj Palace, Teacher Nanak Colony, Tarn Taran Road, Amritsar",
    totalComplaints: 26,
    resolvedComplaints: 16,
    pendingComplaints: 5,
    inProgressComplaints: 5,
    status: "Active",
  },
  {
    id: 46,
    name: "Sh. Navpreet Singh",
    wardNumber: 46,
    area: "Chowk Manna Singh",
    address: "H.No. 2158/13, Gali Miyan Singh, Chowk Manna Singh, Amritsar",
    totalComplaints: 30,
    resolvedComplaints: 19,
    pendingComplaints: 6,
    inProgressComplaints: 5,
    status: "Active",
  },
  {
    id: 47,
    name: "Smt. Kiranjit Kaur",
    wardNumber: 47,
    area: "Guru Ramdas Nagar",
    address: "H.No. 8432, Guru Ramdas Nagar, Amritsar",
    totalComplaints: 22,
    resolvedComplaints: 13,
    pendingComplaints: 4,
    inProgressComplaints: 5,
    status: "Active",
  },
  {
    id: 48,
    name: "Sh. Ashwani Kumar",
    wardNumber: 48,
    area: "Joura Pipal",
    address: "H.No. 986, Gali Devi Wali, Joura Pipal, Kucha Guran Wala, Amritsar",
    totalComplaints: 27,
    resolvedComplaints: 16,
    pendingComplaints: 5,
    inProgressComplaints: 6,
    status: "Active",
  },
  {
    id: 49,
    name: "Smt. Ritu Kundra",
    wardNumber: 49,
    area: "Munshian Bazar",
    address: "4026, Munshian Bazar, Katra Karam Singh, Amritsar",
    totalComplaints: 29,
    resolvedComplaints: 18,
    pendingComplaints: 6,
    inProgressComplaints: 5,
    status: "Active",
  },
  {
    id: 50,
    name: "Smt. Ritu",
    wardNumber: 50,
    area: "Gillwali Gate",
    address: "Gillwali Gate, Dera Baba Ayudhya Das, Amritsar",
    totalComplaints: 21,
    resolvedComplaints: 12,
    pendingComplaints: 4,
    inProgressComplaints: 5,
    status: "Active",
  },
  {
    id: 51,
    name: "Smt. Sarita",
    wardNumber: 51,
    area: "Sahibzada Fateh Singh Nagar",
    address: "150, Gali No. 2 Sahibzada Fateh Singh Nagar, O/S Gate Hakima, Amritsar",
    totalComplaints: 28,
    resolvedComplaints: 17,
    pendingComplaints: 6,
    inProgressComplaints: 5,
    status: "Active",
  },
  {
    id: 52,
    name: "Sh. Vikas Soni",
    wardNumber: 52,
    area: "Rani Ka Bagh",
    address: "115 Rani Ka Bagh, Amritsar",
    totalComplaints: 32,
    resolvedComplaints: 21,
    pendingComplaints: 6,
    inProgressComplaints: 5,
    status: "Active",
  },
  {
    id: 53,
    name: "Smt. Komal Shah",
    wardNumber: 53,
    area: "Shaheed Udham Singh Colony",
    address: "447, Gali No. 11, Shaheed Udham Singh Colony, Gate Khazana, Amritsar",
    totalComplaints: 24,
    resolvedComplaints: 14,
    pendingComplaints: 5,
    inProgressComplaints: 5,
    status: "Active",
  },
  {
    id: 54,
    name: "Sh. Amit Kumar",
    wardNumber: 54,
    area: "Inside Gate Hakima",
    address: "H.No. 3140, Inside Gate Hakima, Amritsar",
    totalComplaints: 31,
    resolvedComplaints: 20,
    pendingComplaints: 6,
    inProgressComplaints: 5,
    status: "Active",
  },
  {
    id: 55,
    name: "Smt. Kulbir Kaur",
    wardNumber: 55,
    area: "Qilla Bhangea",
    address: "H.No. 1713, Qilla Bhangea Kubiberi, Amritsar",
    totalComplaints: 23,
    resolvedComplaints: 13,
    pendingComplaints: 5,
    inProgressComplaints: 5,
    status: "Active",
  },
  {
    id: 56,
    name: "Sh. Varinder Vicky Datta",
    wardNumber: 56,
    area: "Killa Bhangian",
    address: "1431, Killa Bhangian Nimak Mandi, Amritsar",
    totalComplaints: 26,
    resolvedComplaints: 15,
    pendingComplaints: 5,
    inProgressComplaints: 6,
    status: "Active",
  },
  {
    id: 57,
    name: "Smt. Manju Mehra Pappal",
    wardNumber: 57,
    area: "Beri Gate",
    address: "H.No. 793, Gali Bhaian, Beri Gate, Katra Bhai Sant Singh, Amritsar",
    totalComplaints: 28,
    resolvedComplaints: 17,
    pendingComplaints: 5,
    inProgressComplaints: 6,
    status: "Active",
  },
  {
    id: 58,
    name: "Sh. Jarnail Singh",
    wardNumber: 58,
    area: "Inside Sultanwind Gate",
    address: "1707, Talab Pritam Dass, Opp. Sangania Hospital, Inside Sultanwind Gate, Amritsar",
    totalComplaints: 30,
    resolvedComplaints: 19,
    pendingComplaints: 6,
    inProgressComplaints: 5,
    status: "Active",
  },
  {
    id: 59,
    name: "Smt. Gurmeet Kaur",
    wardNumber: 59,
    area: "Kot Mana Singh",
    address: "1-9-149, Tarn Taran Road, Kot Mana Singh, Amritsar",
    totalComplaints: 25,
    resolvedComplaints: 15,
    pendingComplaints: 5,
    inProgressComplaints: 5,
    status: "Active",
  },
  {
    id: 60,
    name: "Sh. Gaurav Gill",
    wardNumber: 60,
    area: "Kashmir Avenue",
    address: "H.No. F-1/395, Kashmir Avenue, Majitha Road, Amritsar",
    totalComplaints: 34,
    resolvedComplaints: 22,
    pendingComplaints: 6,
    inProgressComplaints: 6,
    status: "Active",
  },
  {
    id: 61,
    name: "Smt. Rajni",
    wardNumber: 61,
    area: "Shivala Colony",
    address: "113 Shivala Colony, Amritsar",
    totalComplaints: 20,
    resolvedComplaints: 11,
    pendingComplaints: 4,
    inProgressComplaints: 5,
    status: "Active",
  },
  {
    id: 62,
    name: "Sh. Sameer Dutta",
    wardNumber: 62,
    area: "Dhariwal Hospital Area",
    address: "343 Near Dhariwal Hospital, Amritsar",
    totalComplaints: 27,
    resolvedComplaints: 16,
    pendingComplaints: 5,
    inProgressComplaints: 6,
    status: "Active",
  },
  {
    id: 63,
    name: "Smt. Usha Rani",
    wardNumber: 63,
    area: "Islamabad",
    address: "H.No. 2015/16, Gali Bank Wali, Islamabad, Amritsar",
    totalComplaints: 29,
    resolvedComplaints: 18,
    pendingComplaints: 6,
    inProgressComplaints: 5,
    status: "Active",
  },
  {
    id: 64,
    name: "Smt. Neetu Tangri",
    wardNumber: 64,
    area: "Model Town",
    address: "21, Model Town Street No. 1, Rani Ka Bagh, Amritsar",
    totalComplaints: 31,
    resolvedComplaints: 20,
    pendingComplaints: 6,
    inProgressComplaints: 5,
    status: "Active",
  },
  {
    id: 65,
    name: "Smt. Neeraj Chaudhary",
    wardNumber: 65,
    area: "Putlighar",
    address: "2611 Street No. 1, Shimla Market, Putlighar, Amritsar",
    totalComplaints: 24,
    resolvedComplaints: 14,
    pendingComplaints: 5,
    inProgressComplaints: 5,
    status: "Active",
  },
  {
    id: 66,
    name: "Sh. Virat Devgan",
    wardNumber: 66,
    area: "Kabir Park",
    address: "H.No. 75, Kabir Park, Opposite GNDU Park, Amritsar",
    totalComplaints: 33,
    resolvedComplaints: 21,
    pendingComplaints: 6,
    inProgressComplaints: 6,
    status: "Active",
  },
  {
    id: 67,
    name: "Smt. Anita (Deputy Mayor)",
    wardNumber: 67,
    area: "Islamabad",
    address: "H.No. 2015/16, Gali Bank Wali, Islamabad, Amritsar",
    totalComplaints: 30,
    resolvedComplaints: 19,
    pendingComplaints: 6,
    inProgressComplaints: 5,
    status: "Active",
  },
  {
    id: 68,
    name: "Sh. Vikas Gill",
    wardNumber: 68,
    area: "Amrik Singh Nagar",
    address: "H.No. 6573, Amrik Singh Nagar, O/S Lahori Gate, Amritsar",
    totalComplaints: 26,
    resolvedComplaints: 15,
    pendingComplaints: 5,
    inProgressComplaints: 6,
    status: "Active",
  },
  {
    id: 69,
    name: "Smt. Gurpreet Kaur",
    wardNumber: 69,
    area: "Meharpura",
    address: "H.No. 5266 Gali No. 28, Meharpura, Amritsar",
    totalComplaints: 22,
    resolvedComplaints: 13,
    pendingComplaints: 4,
    inProgressComplaints: 5,
    status: "Active",
  },
  {
    id: 70,
    name: "Sh. Vijay Kumar",
    wardNumber: 70,
    area: "Chota Haripura",
    address: "D/2-828, Chota Haripura, Amritsar",
    totalComplaints: 28,
    resolvedComplaints: 17,
    pendingComplaints: 6,
    inProgressComplaints: 5,
    status: "Active",
  },
  {
    id: 71,
    name: "Smt. Surjit Kaur",
    wardNumber: 71,
    area: "Guru Nanakpura",
    address: "128, Street No. 8, Guru Nanakpura, Amritsar",
    totalComplaints: 23,
    resolvedComplaints: 13,
    pendingComplaints: 5,
    inProgressComplaints: 5,
    status: "Active",
  },
  {
    id: 72,
    name: "Sh. Avtar Singh",
    wardNumber: 72,
    area: "Dhapai",
    address: "D4/239, Dhapai, Amritsar",
    totalComplaints: 27,
    resolvedComplaints: 16,
    pendingComplaints: 5,
    inProgressComplaints: 6,
    status: "Active",
  },
  {
    id: 73,
    name: "Sh. Kuldeep Singh",
    wardNumber: 73,
    area: "Baba Jiwan Singh Colony",
    address: "184/31 Baba Jiwan Singh Colony, Angarh, Amritsar",
    totalComplaints: 29,
    resolvedComplaints: 18,
    pendingComplaints: 6,
    inProgressComplaints: 5,
    status: "Active",
  },
  {
    id: 74,
    name: "Smt. Paramjit Kaur Dhillon",
    wardNumber: 74,
    area: "Holicity Pearl",
    address: "5, Holicity Pearl, Bypass Road, Amritsar",
    totalComplaints: 21,
    resolvedComplaints: 12,
    pendingComplaints: 4,
    inProgressComplaints: 5,
    status: "Active",
  },
  {
    id: 75,
    name: "Sh. Kashmir Singh",
    wardNumber: 75,
    area: "Hargobindpura",
    address: "Guru Ki Wadali Road, Hargobindpura, Chheharta, Amritsar",
    totalComplaints: 26,
    resolvedComplaints: 15,
    pendingComplaints: 5,
    inProgressComplaints: 6,
    status: "Active",
  },
  {
    id: 76,
    name: "Sh. Sukhbir Singh",
    wardNumber: 76,
    area: "Kot Khalsa",
    address: "D-6/559, Police Station Street, Kot Khalsa, Amritsar",
    totalComplaints: 31,
    resolvedComplaints: 20,
    pendingComplaints: 6,
    inProgressComplaints: 5,
    status: "Active",
  },
  {
    id: 77,
    name: "Smt. Sunita",
    wardNumber: 77,
    area: "Chheharta",
    address: "E-7/4673, Majeed Building, Chheharta, Amritsar",
    totalComplaints: 24,
    resolvedComplaints: 14,
    pendingComplaints: 5,
    inProgressComplaints: 5,
    status: "Active",
  },
  {
    id: 78,
    name: "Smt. Anita Sharma",
    wardNumber: 78,
    area: "Japanese Avenue",
    address: "H.No. J-14, Japanese Avenue, Near Bharat Hospital, Chheharta, Amritsar",
    totalComplaints: 30,
    resolvedComplaints: 19,
    pendingComplaints: 6,
    inProgressComplaints: 5,
    status: "Active",
  },
  {
    id: 79,
    name: "Smt. Shivali",
    wardNumber: 79,
    area: "Old Lal Mill",
    address: "E5/3063 Subhash Road, Old Lal Mill, Chheharta, Amritsar",
    totalComplaints: 22,
    resolvedComplaints: 13,
    pendingComplaints: 4,
    inProgressComplaints: 5,
    status: "Active",
  },
  {
    id: 80,
    name: "Sh. Raman Kumar",
    wardNumber: 80,
    area: "New Ranjitpura",
    address: "H.No. E7/526, Street No. 2, New Ranjitpura, Chheharta, Amritsar",
    totalComplaints: 28,
    resolvedComplaints: 17,
    pendingComplaints: 6,
    inProgressComplaints: 5,
    status: "Active",
  },
  {
    id: 81,
    name: "Smt. Nisha Dhillon",
    wardNumber: 81,
    area: "Shamsher Nagar",
    address: "2 Shamsher Nagar, Khandwala, Chheharta, Amritsar",
    totalComplaints: 23,
    resolvedComplaints: 13,
    pendingComplaints: 5,
    inProgressComplaints: 5,
    status: "Active",
  },
  {
    id: 82,
    name: "Sh. Sandeep Singh",
    wardNumber: 82,
    area: "Village Kale",
    address: "Village Kale, Chheharta, Amritsar",
    totalComplaints: 27,
    resolvedComplaints: 16,
    pendingComplaints: 5,
    inProgressComplaints: 6,
    status: "Active",
  },
  {
    id: 83,
    name: "Smt. Nagwant Kaur",
    wardNumber: 83,
    area: "Dashmesh Nagar",
    address: "56/57, Polytechnic Road, Near GNDU, Dashmesh Nagar, Amritsar",
    totalComplaints: 25,
    resolvedComplaints: 15,
    pendingComplaints: 5,
    inProgressComplaints: 5,
    status: "Active",
  },
  {
    id: 84,
    name: "Sh. Rashpal Singh",
    wardNumber: 84,
    area: "Kabir Park",
    address: "313, Kabir Park, Amritsar",
    totalComplaints: 29,
    resolvedComplaints: 18,
    pendingComplaints: 6,
    inProgressComplaints: 5,
    status: "Active",
  },
  {
    id: 85,
    name: "Smt. Nitasha Gill",
    wardNumber: 85,
    area: "New Anmol Enclave",
    address: "H.No. 25, New Anmol Enclave, Ram Tirth Road, Amritsar",
    totalComplaints: 24,
    resolvedComplaints: 14,
    pendingComplaints: 5,
    inProgressComplaints: 5,
    status: "Active",
  },
];
